package com.dd.mcps.entities;

// Generated Jul 1, 2015 2:40:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * McpsPartneraccount generated by hbm2java
 */
@Entity
@Table(name = "mcps_partneraccount", catalog = "mcps")
public class McpsPartneraccount implements java.io.Serializable {

	private long id;
	private McpsAccount mcpsAccount;
	private Long accountId;
	private String partnerName;
	private Date foundingDate;
	private String address;
	private String tel;
	private String website;

	public McpsPartneraccount() {
	}

	public McpsPartneraccount(McpsAccount mcpsAccount, String partnerName,
			String address, String tel) {
		this.mcpsAccount = mcpsAccount;
		this.partnerName = partnerName;
		this.address = address;
		this.tel = tel;
	}

	public McpsPartneraccount(McpsAccount mcpsAccount, Long accountId,
			String partnerName, Date foundingDate, String address, String tel,
			String website) {
		this.mcpsAccount = mcpsAccount;
		this.accountId = accountId;
		this.partnerName = partnerName;
		this.foundingDate = foundingDate;
		this.address = address;
		this.tel = tel;
		this.website = website;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "mcpsAccount"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public McpsAccount getMcpsAccount() {
		return this.mcpsAccount;
	}

	public void setMcpsAccount(McpsAccount mcpsAccount) {
		this.mcpsAccount = mcpsAccount;
	}

	@Column(name = "AccountID")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "PartnerName", nullable = false)
	public String getPartnerName() {
		return this.partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FoundingDate", length = 10)
	public Date getFoundingDate() {
		return this.foundingDate;
	}

	public void setFoundingDate(Date foundingDate) {
		this.foundingDate = foundingDate;
	}

	@Column(name = "Address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Tel", nullable = false)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "Website")
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

}
