package com.dd.mcps.entities;

// Generated Jun 15, 2015 5:48:45 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * McpsCampaignAccount generated by hbm2java
 */
@Entity
@Table(name = "mcps_campaign_account", catalog = "mcps")
public class McpsCampaignAccount implements java.io.Serializable {

	private McpsCampaignAccountId id;
	private McpsReview mcpsReview;
	private McpsAccount mcpsAccount;
	private McpsCampaign mcpsCampaign;
	private Byte rate;
	private boolean notification;

	public McpsCampaignAccount() {
	}

	public McpsCampaignAccount(McpsCampaignAccountId id,
			McpsAccount mcpsAccount, McpsCampaign mcpsCampaign,
			boolean notification) {
		this.id = id;
		this.mcpsAccount = mcpsAccount;
		this.mcpsCampaign = mcpsCampaign;
		this.notification = notification;
	}

	public McpsCampaignAccount(McpsCampaignAccountId id, McpsReview mcpsReview,
			McpsAccount mcpsAccount, McpsCampaign mcpsCampaign, Byte rate,
			boolean notification) {
		this.id = id;
		this.mcpsReview = mcpsReview;
		this.mcpsAccount = mcpsAccount;
		this.mcpsCampaign = mcpsCampaign;
		this.rate = rate;
		this.notification = notification;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "campaignId", column = @Column(name = "CampaignID", nullable = false)),
			@AttributeOverride(name = "accountId", column = @Column(name = "AccountID", nullable = false)) })
	public McpsCampaignAccountId getId() {
		return this.id;
	}

	public void setId(McpsCampaignAccountId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ReviewID")
	public McpsReview getMcpsReview() {
		return this.mcpsReview;
	}

	public void setMcpsReview(McpsReview mcpsReview) {
		this.mcpsReview = mcpsReview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountID", nullable = false, insertable = false, updatable = false)
	public McpsAccount getMcpsAccount() {
		return this.mcpsAccount;
	}

	public void setMcpsAccount(McpsAccount mcpsAccount) {
		this.mcpsAccount = mcpsAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CampaignID", nullable = false, insertable = false, updatable = false)
	public McpsCampaign getMcpsCampaign() {
		return this.mcpsCampaign;
	}

	public void setMcpsCampaign(McpsCampaign mcpsCampaign) {
		this.mcpsCampaign = mcpsCampaign;
	}

	@Column(name = "Rate")
	public Byte getRate() {
		return this.rate;
	}

	public void setRate(Byte rate) {
		this.rate = rate;
	}

	@Column(name = "Notification", nullable = false)
	public boolean isNotification() {
		return this.notification;
	}

	public void setNotification(boolean notification) {
		this.notification = notification;
	}

}
