package com.dd.mcps.entities;

// Generated Jul 1, 2015 2:40:35 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * McpsOption generated by hbm2java
 */
@Entity
@Table(name = "mcps_option", catalog = "mcps")
public class McpsOption implements java.io.Serializable {

	private McpsOptionId id;
	private McpsSurveyquestion mcpsSurveyquestion;
	private String content;

	public McpsOption() {
	}

	public McpsOption(McpsOptionId id, McpsSurveyquestion mcpsSurveyquestion) {
		this.id = id;
		this.mcpsSurveyquestion = mcpsSurveyquestion;
	}

	public McpsOption(McpsOptionId id, McpsSurveyquestion mcpsSurveyquestion,
			String content) {
		this.id = id;
		this.mcpsSurveyquestion = mcpsSurveyquestion;
		this.content = content;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "optionId", column = @Column(name = "OptionID", nullable = false)),
			@AttributeOverride(name = "surveyQuestionId", column = @Column(name = "SurveyQuestionID", nullable = false)) })
	public McpsOptionId getId() {
		return this.id;
	}

	public void setId(McpsOptionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SurveyQuestionID", nullable = false, insertable = false, updatable = false)
	public McpsSurveyquestion getMcpsSurveyquestion() {
		return this.mcpsSurveyquestion;
	}

	public void setMcpsSurveyquestion(McpsSurveyquestion mcpsSurveyquestion) {
		this.mcpsSurveyquestion = mcpsSurveyquestion;
	}

	@Column(name = "Content", length = 2000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
