package com.dd.mcps.entities;

// Generated Jul 1, 2015 2:40:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * McpsGender generated by hbm2java
 */
@Entity
@Table(name = "mcps_gender", catalog = "mcps")
public class McpsGender implements java.io.Serializable {

	private Byte id;
	private String genderName;
	private Set<McpsRevieweraccount> mcpsRevieweraccounts = new HashSet<McpsRevieweraccount>(
			0);

	public McpsGender() {
	}

	public McpsGender(String genderName,
			Set<McpsRevieweraccount> mcpsRevieweraccounts) {
		this.genderName = genderName;
		this.mcpsRevieweraccounts = mcpsRevieweraccounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Byte getId() {
		return this.id;
	}

	public void setId(Byte id) {
		this.id = id;
	}

	@Column(name = "GenderName")
	public String getGenderName() {
		return this.genderName;
	}

	public void setGenderName(String genderName) {
		this.genderName = genderName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mcpsGender")
	public Set<McpsRevieweraccount> getMcpsRevieweraccounts() {
		return this.mcpsRevieweraccounts;
	}

	public void setMcpsRevieweraccounts(
			Set<McpsRevieweraccount> mcpsRevieweraccounts) {
		this.mcpsRevieweraccounts = mcpsRevieweraccounts;
	}

}
