package com.dd.mcps.entities;

// Generated Jul 1, 2015 2:40:35 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * McpsAnswer generated by hbm2java
 */
@Entity
@Table(name = "mcps_answer", catalog = "mcps")
public class McpsAnswer implements java.io.Serializable {

	private long id;
	private McpsRevieweraccountSurvey mcpsRevieweraccountSurvey;
	private McpsSurveyquestion mcpsSurveyquestion;
	private String answerInText;
	private Byte answerByNumber;

	public McpsAnswer() {
	}

	public McpsAnswer(long id,
			McpsRevieweraccountSurvey mcpsRevieweraccountSurvey,
			McpsSurveyquestion mcpsSurveyquestion) {
		this.id = id;
		this.mcpsRevieweraccountSurvey = mcpsRevieweraccountSurvey;
		this.mcpsSurveyquestion = mcpsSurveyquestion;
	}

	public McpsAnswer(long id,
			McpsRevieweraccountSurvey mcpsRevieweraccountSurvey,
			McpsSurveyquestion mcpsSurveyquestion, String answerInText,
			Byte answerByNumber) {
		this.id = id;
		this.mcpsRevieweraccountSurvey = mcpsRevieweraccountSurvey;
		this.mcpsSurveyquestion = mcpsSurveyquestion;
		this.answerInText = answerInText;
		this.answerByNumber = answerByNumber;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ReviewerAccount_SurveyID", nullable = false)
	public McpsRevieweraccountSurvey getMcpsRevieweraccountSurvey() {
		return this.mcpsRevieweraccountSurvey;
	}

	public void setMcpsRevieweraccountSurvey(
			McpsRevieweraccountSurvey mcpsRevieweraccountSurvey) {
		this.mcpsRevieweraccountSurvey = mcpsRevieweraccountSurvey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QuestionID", nullable = false)
	public McpsSurveyquestion getMcpsSurveyquestion() {
		return this.mcpsSurveyquestion;
	}

	public void setMcpsSurveyquestion(McpsSurveyquestion mcpsSurveyquestion) {
		this.mcpsSurveyquestion = mcpsSurveyquestion;
	}

	@Column(name = "AnswerInText", length = 2000)
	public String getAnswerInText() {
		return this.answerInText;
	}

	public void setAnswerInText(String answerInText) {
		this.answerInText = answerInText;
	}

	@Column(name = "AnswerByNumber")
	public Byte getAnswerByNumber() {
		return this.answerByNumber;
	}

	public void setAnswerByNumber(Byte answerByNumber) {
		this.answerByNumber = answerByNumber;
	}

}
