package com.dd.mcps.entities;

// Generated Jun 16, 2015 2:25:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * McpsAccount generated by hbm2java
 */
@Entity
@Table(name = "mcps_account", catalog = "mcps", uniqueConstraints = @UniqueConstraint(columnNames = "Email"))
public class McpsAccount implements java.io.Serializable {

	private Long id;
	private McpsRole mcpsRole;
	private String email;
	private String pass;
	private String state;
	private Set<McpsCampaignAccount> mcpsCampaignAccounts = new HashSet<McpsCampaignAccount>(
			0);
	private McpsPartneraccount mcpsPartneraccount;
	private Set<McpsCampaign> mcpsCampaigns = new HashSet<McpsCampaign>(0);
	private McpsRevieweraccount mcpsRevieweraccount;

	public McpsAccount() {
	}

	public McpsAccount(String email, String pass) {
		this.email = email;
		this.pass = pass;
	}

	public McpsAccount(McpsRole mcpsRole, String email, String pass,
			String state, Set<McpsCampaignAccount> mcpsCampaignAccounts,
			McpsPartneraccount mcpsPartneraccount,
			Set<McpsCampaign> mcpsCampaigns,
			McpsRevieweraccount mcpsRevieweraccount) {
		this.mcpsRole = mcpsRole;
		this.email = email;
		this.pass = pass;
		this.state = state;
		this.mcpsCampaignAccounts = mcpsCampaignAccounts;
		this.mcpsPartneraccount = mcpsPartneraccount;
		this.mcpsCampaigns = mcpsCampaigns;
		this.mcpsRevieweraccount = mcpsRevieweraccount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoleType")
	public McpsRole getMcpsRole() {
		return this.mcpsRole;
	}

	public void setMcpsRole(McpsRole mcpsRole) {
		this.mcpsRole = mcpsRole;
	}

	@Column(name = "Email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Pass", nullable = false)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "State")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mcpsAccount")
	public Set<McpsCampaignAccount> getMcpsCampaignAccounts() {
		return this.mcpsCampaignAccounts;
	}

	public void setMcpsCampaignAccounts(
			Set<McpsCampaignAccount> mcpsCampaignAccounts) {
		this.mcpsCampaignAccounts = mcpsCampaignAccounts;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "mcpsAccount")
	public McpsPartneraccount getMcpsPartneraccount() {
		return this.mcpsPartneraccount;
	}

	public void setMcpsPartneraccount(McpsPartneraccount mcpsPartneraccount) {
		this.mcpsPartneraccount = mcpsPartneraccount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mcpsAccount")
	public Set<McpsCampaign> getMcpsCampaigns() {
		return this.mcpsCampaigns;
	}

	public void setMcpsCampaigns(Set<McpsCampaign> mcpsCampaigns) {
		this.mcpsCampaigns = mcpsCampaigns;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "mcpsAccount")
	public McpsRevieweraccount getMcpsRevieweraccount() {
		return this.mcpsRevieweraccount;
	}

	public void setMcpsRevieweraccount(McpsRevieweraccount mcpsRevieweraccount) {
		this.mcpsRevieweraccount = mcpsRevieweraccount;
	}

}
